# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5095cced8d92a407d4ecfadef0dade5f211c8e62af89ad20004d0fa767a77b9bf726646b8d58c34df36c64fb244ab59934c4919cd409d2457193073017ba6383

test:
  secret_key_base: a3ee4b41c32a69f2d5fcfdfc8dac55ef3b4a1b28f323ea07fd618bbc46ff166f5263fcce2ed1d850c68f22b11c7df49fcaa3dc1a6799e74fc5a5b07bd731e468

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
